# Generated by Django 4.2.2 on 2023-06-20 15:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Georeferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('poligono', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('multipunto', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('multipoligono', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'georefencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('Masculino', 'MASCULINO'), ('Femenino', 'FEMENINO')], max_length=10)),
                ('medalla', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10)),
                ('ci', models.IntegerField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apptroncal.servicio')),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
    ]
